name: 'Run Agent'
description: 'Check out agent harness and run an agent role or orchestration script'

inputs:
  entry-point:
    description: 'Script to run relative to harness root (e.g., agents/engineer.sh, scripts/run-sre.sh)'
    required: true
  harness-ref:
    description: 'Git ref for harness repo checkout'
    default: 'main'
  azure-storage-account:
    description: 'Azure storage account for usage data'
    default: 'agentfishbowlstorage'
  azure-usage-container:
    description: 'Blob container for usage data'
    default: 'agent-usage'

runs:
  using: 'composite'
  steps:
    - name: Checkout harness
      uses: actions/checkout@v4
      with:
        repository: YourMoveLabs/agent-harness
        ref: ${{ inputs.harness-ref }}
        path: .harness

    - name: Set up environment
      shell: bash
      run: |
        echo "HARNESS_ROOT=${{ github.workspace }}/.harness" >> "$GITHUB_ENV"
        echo "PROJECT_ROOT=${{ github.workspace }}" >> "$GITHUB_ENV"

        # Load .env: prefer project root, fall back to runner config
        if [ -f "${{ github.workspace }}/.env" ]; then
          echo "Using .env from project root"
        elif [ -f "$HOME/.config/agent-harness/.env" ]; then
          cp "$HOME/.config/agent-harness/.env" "${{ github.workspace }}/.env"
          echo "Loaded .env from runner config"
        else
          echo "WARNING: No .env found"
        fi

    - name: Run agent
      shell: bash
      run: |
        chmod +x ".harness/${{ inputs.entry-point }}"
        ".harness/${{ inputs.entry-point }}"

    - name: Post usage summary
      if: always()
      shell: bash
      run: |
        USAGE_DIR="/tmp/agent-logs"
        USAGE_FILES=$(ls "$USAGE_DIR"/*-usage.json 2>/dev/null || true)

        if [ -z "$USAGE_FILES" ]; then
          echo "No usage data found (agent may not have produced JSON output)" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        # Post summary for each agent (handles multi-agent workflows)
        for USAGE_FILE in $USAGE_FILES; do
          COST=$(jq -r '.total_cost_usd // "?"' "$USAGE_FILE")
          TURNS=$(jq -r '.num_turns // "?"' "$USAGE_FILE")
          DURATION=$(jq -r '(.duration_api_ms // 0) / 1000 | floor' "$USAGE_FILE")
          ROLE=$(jq -r '.role // "unknown"' "$USAGE_FILE")

          echo "### Agent Usage: ${ROLE}" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Metric | Value |" >> "$GITHUB_STEP_SUMMARY"
          echo "|--------|-------|" >> "$GITHUB_STEP_SUMMARY"
          echo "| Cost | \$${COST} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Turns | ${TURNS} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| API Duration | ${DURATION}s |" >> "$GITHUB_STEP_SUMMARY"

          # Add per-model breakdown if available
          if jq -e '.model_usage | length > 0' "$USAGE_FILE" >/dev/null 2>&1; then
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "**Model breakdown:**" >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "| Model | Input | Output | Cost |" >> "$GITHUB_STEP_SUMMARY"
            echo "|-------|-------|--------|------|" >> "$GITHUB_STEP_SUMMARY"
            jq -r '.model_usage | to_entries[] | "| \(.key) | \(.value.inputTokens) | \(.value.outputTokens) | $\(.value.costUSD) |"' "$USAGE_FILE" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "" >> "$GITHUB_STEP_SUMMARY"
        done

    - name: Upload usage to blob
      if: always()
      shell: bash
      run: |
        USAGE_DIR="/tmp/agent-logs"
        USAGE_FILES=$(ls "$USAGE_DIR"/*-usage.json 2>/dev/null || true)
        [ -z "$USAGE_FILES" ] && exit 0

        # Merge all usage files into a single envelope
        MERGED="$USAGE_DIR/usage-merged.json"
        jq -s '{
          run_id: $run_id,
          run_url: $run_url,
          agents: .
        }' \
          --arg run_id "${{ github.run_id }}" \
          --arg run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          $USAGE_FILES > "$MERGED"

        # Login with user-assigned Managed Identity
        az login --identity --client-id "$MANAGED_IDENTITY_CLIENT_ID" --output none 2>/dev/null || {
          echo "WARNING: Azure login failed — skipping usage upload"
          exit 0
        }

        # Upload to blob storage
        az storage blob upload \
          --account-name "${{ inputs.azure-storage-account }}" \
          --container-name "${{ inputs.azure-usage-container }}" \
          --name "${{ github.run_id }}.json" \
          --file "$MERGED" \
          --content-type "application/json" \
          --auth-mode login \
          --overwrite 2>/dev/null || echo "WARNING: Blob upload failed (non-fatal)"
