name: 'Run Agent'
description: 'Check out agent harness and run an agent role or orchestration script'

inputs:
  role:
    description: 'Agent role from config/roles.json (e.g., engineer, reviewer, product-owner). Mutually exclusive with entry-point.'
    required: false
  job:
    description: 'Job to run for the given role (from agents/prompts/jobs/{role}/). Loads identity + job instructions instead of monolithic prompt. Requires role input.'
    required: false
  entry-point:
    description: 'Script to run relative to harness root (e.g., scripts/run-site-reliability.sh). Mutually exclusive with role.'
    required: false
  harness-ref:
    description: 'Git ref for harness repo checkout'
    default: 'main'
  azure-storage-account:
    description: 'Azure storage account for usage data'
    default: 'agentfishbowlstorage'
  azure-usage-container:
    description: 'Blob container for usage data'
    default: 'agent-usage'

runs:
  using: 'composite'
  steps:
    - name: Checkout harness
      uses: actions/checkout@v4
      with:
        repository: YourMoveLabs/agent-harness
        ref: ${{ inputs.harness-ref }}
        path: .harness

    - name: Set up environment
      shell: bash
      run: |
        echo "HARNESS_ROOT=${{ github.workspace }}/.harness" >> "$GITHUB_ENV"
        echo "PROJECT_ROOT=${{ github.workspace }}" >> "$GITHUB_ENV"

        # Load .env: prefer project root, fall back to runner config
        if [ -f "${{ github.workspace }}/.env" ]; then
          echo "Using .env from project root"
        elif [ -f "$HOME/.config/agent-harness/.env" ]; then
          cp "$HOME/.config/agent-harness/.env" "${{ github.workspace }}/.env"
          echo "Loaded .env from runner config"
        else
          echo "WARNING: No .env found"
        fi

    - name: Clean agent logs
      shell: bash
      run: rm -rf /tmp/agent-logs && mkdir -p /tmp/agent-logs

    - name: Chain depth guard
      shell: bash
      run: |
        DEPTH="${AGENT_CHAIN_DEPTH:-0}"
        echo "Chain depth: $DEPTH"
        if [ "$DEPTH" -ge 5 ]; then
          echo "::warning::Chain depth $DEPTH >= 5 — halting to prevent infinite dispatch loop"
          echo "Chain depth limit reached — halting." >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dev tools
      shell: bash
      run: pip install ruff

    - name: Enable project git hooks
      shell: bash
      run: |
        if [ -d ".githooks" ]; then
          git config core.hooksPath .githooks
          chmod +x .githooks/*
          echo "Git hooks enabled from .githooks/"
        fi

    - name: Run agent
      shell: bash
      run: |
        if [ -n "${{ inputs.role }}" ]; then
          # Direct role invocation — no wrapper script needed
          chmod +x ".harness/agents/run-agent.sh"
          JOB_ARG=""
          if [ -n "${{ inputs.job }}" ]; then
            JOB_ARG="--job ${{ inputs.job }}"
          fi
          ".harness/agents/run-agent.sh" "${{ inputs.role }}" $JOB_ARG
        elif [ -n "${{ inputs.entry-point }}" ]; then
          # Orchestration script invocation
          chmod +x ".harness/${{ inputs.entry-point }}"
          ".harness/${{ inputs.entry-point }}"
        else
          echo "ERROR: Either 'role' or 'entry-point' input is required"
          exit 1
        fi

    - name: Post usage summary
      if: always()
      shell: bash
      run: |
        USAGE_DIR="/tmp/agent-logs"
        USAGE_FILES=$(ls "$USAGE_DIR"/*-usage.json 2>/dev/null || true)

        if [ -z "$USAGE_FILES" ]; then
          echo "No agent invoked — nothing to report." >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        # Post summary for each agent (handles multi-agent workflows)
        for USAGE_FILE in $USAGE_FILES; do
          COST=$(jq -r '.total_cost_usd // "?"' "$USAGE_FILE")
          TURNS=$(jq -r '.num_turns // "?"' "$USAGE_FILE")
          DURATION=$(jq -r '(.duration_api_ms // 0) / 1000 | floor' "$USAGE_FILE")
          ROLE=$(jq -r '.role // "unknown"' "$USAGE_FILE")

          echo "### Agent Usage: ${ROLE}" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Metric | Value |" >> "$GITHUB_STEP_SUMMARY"
          echo "|--------|-------|" >> "$GITHUB_STEP_SUMMARY"
          echo "| Cost | \$${COST} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Turns | ${TURNS} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| API Duration | ${DURATION}s |" >> "$GITHUB_STEP_SUMMARY"

          # Add per-model breakdown if available
          if jq -e '.model_usage | length > 0' "$USAGE_FILE" >/dev/null 2>&1; then
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "**Model breakdown:**" >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "| Model | Input | Output | Cost |" >> "$GITHUB_STEP_SUMMARY"
            echo "|-------|-------|--------|------|" >> "$GITHUB_STEP_SUMMARY"
            jq -r '.model_usage | to_entries[] | "| \(.key) | \(.value.inputTokens) | \(.value.outputTokens) | $\(.value.costUSD) |"' "$USAGE_FILE" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "" >> "$GITHUB_STEP_SUMMARY"
        done

    - name: Post agent decision output
      if: always()
      shell: bash
      run: |
        USAGE_DIR="/tmp/agent-logs"
        LOG_FILES=$(ls "$USAGE_DIR"/*.log 2>/dev/null | grep -v '\.stderr' || true)
        [ -z "$LOG_FILES" ] && exit 0

        for LOG_FILE in $LOG_FILES; do
          ROLE=$(basename "$LOG_FILE" | sed 's/-[0-9].*$//')
          LINE_COUNT=$(wc -l < "$LOG_FILE")

          echo "### Agent Output: ${ROLE}" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          if [ "$LINE_COUNT" -le 100 ]; then
            echo '<details open><summary>Full output ('$LINE_COUNT' lines)</summary>' >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            cat "$LOG_FILE" >> "$GITHUB_STEP_SUMMARY"
          else
            echo '<details><summary>Output (last 100 of '$LINE_COUNT' lines)</summary>' >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            tail -100 "$LOG_FILE" >> "$GITHUB_STEP_SUMMARY"
          fi

          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '</details>' >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
        done

    - name: Workspace cleanup
      if: always()
      shell: bash
      run: |
        git gc --auto --quiet 2>/dev/null || true
        git worktree prune 2>/dev/null || true
        NPM_SIZE=$(du -sm ~/.npm 2>/dev/null | cut -f1)
        if [ "${NPM_SIZE:-0}" -gt 500 ]; then
          npm cache clean --force 2>/dev/null || true
        fi

    - name: Upload usage to blob
      if: always()
      shell: bash
      run: |
        USAGE_DIR="/tmp/agent-logs"
        USAGE_FILES=$(ls "$USAGE_DIR"/*-usage.json 2>/dev/null || true)
        [ -z "$USAGE_FILES" ] && exit 0

        # Inject agent result summary into each usage file
        for USAGE_FILE in $USAGE_FILES; do
          LOG_FILE="${USAGE_FILE%-usage.json}.log"
          if [ -f "$LOG_FILE" ]; then
            SUMMARY=$(tail -50 "$LOG_FILE")
            jq --arg summary "$SUMMARY" '. + {result_summary: $summary}' "$USAGE_FILE" > "${USAGE_FILE}.tmp"
            mv "${USAGE_FILE}.tmp" "$USAGE_FILE"
          fi
        done

        # Merge all usage files into a single envelope
        MERGED="$USAGE_DIR/usage-merged.json"
        jq -s '{
          run_id: $run_id,
          run_url: $run_url,
          agents: .
        }' \
          --arg run_id "${{ github.run_id }}" \
          --arg run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          $USAGE_FILES > "$MERGED"

        # Login with user-assigned Managed Identity
        az login --identity --client-id "$MANAGED_IDENTITY_CLIENT_ID" --output none 2>/dev/null || {
          echo "WARNING: Azure login failed — skipping usage upload"
          exit 0
        }

        # Upload to blob storage
        az storage blob upload \
          --account-name "${{ inputs.azure-storage-account }}" \
          --container-name "${{ inputs.azure-usage-container }}" \
          --name "${{ github.run_id }}.json" \
          --file "$MERGED" \
          --content-type "application/json" \
          --auth-mode login \
          --overwrite 2>/dev/null || echo "WARNING: Blob upload failed (non-fatal)"
